#!/bin/bash
# i3 brightness using brightnessctl
# created by : C0SM0

current_brightness=$(brightnessctl g)
max_brightness=$(brightnessctl m)

# Calculate the percentage of num1 with respect to num2
percentage=$(echo "scale=2; $current_brightness/$max_brightness*100" | bc)

# Print the result
echo "$percentage%"
