#!/bin/bash
# i3 volume control

# Get the name of the default sink
sink_name=$(pactl info | grep 'Default Sink' | awk '{print $3}')

# Run pactl command and capture the output
output=$(pactl list sinks | grep -A 15 "Name: $sink_name" | awk '/Volume:/{print $5; exit}')

# Extract the volume percentage using string manipulation
volume=$(echo "$output" | tr -d '%')

# Check if the sink is muted
mute_status=$(pactl list sinks | grep -A 15 "Name: $sink_name" | awk '/Mute/{print $2; exit}')

# Print the volume level or mute status
if [ "$mute_status" == "yes" ]; then
    echo "VOL: <span foreground='#999999'>MUTED</span>"
else
    echo "VOL: <span foreground='#999999'>$volume%</span>"
fi


# Define click events
case $BLOCK_BUTTON in
    1)  # Left click: Toggle mute
        pactl set-sink-mute "$sink_name" toggle
        ;;
    4)  # Scroll up: Increase volume
        pactl set-sink-volume "$sink_name" +5%
        ;;
    5)  # Scroll down: Decrease volume
        pactl set-sink-volume "$sink_name" -5%
        ;;
esac

